"""image-url

Revision ID: 163074400914
Revises: 54c80f6bdfd2
Create Date: 2026-02-08 17:07:37.192485

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "163074400914"
down_revision = "54c80f6bdfd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode",
        sa.Column(
            "image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episode", "image_url")
    # ### end Alembic commands ###
